--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.4

-- Started on 2024-12-11 01:05:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 24609)
-- Name: Cesfampage_evento; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public."Cesfampage_evento" (
    id bigint NOT NULL,
    titulo character varying(100) NOT NULL,
    imagen character varying(100) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    descripcion text,
    tipo_evento character varying(50) NOT NULL
);


ALTER TABLE public."Cesfampage_evento" OWNER TO inacap;

--
-- TOC entry 217 (class 1259 OID 24608)
-- Name: Cesfampage_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public."Cesfampage_evento" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cesfampage_evento_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24633)
-- Name: Cesfampage_noticia; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public."Cesfampage_noticia" (
    id bigint NOT NULL,
    titulo character varying(100) NOT NULL,
    imagen character varying(100) NOT NULL,
    descripcion text,
    fecha_creacion timestamp with time zone NOT NULL,
    evento_relacionado_id bigint
);


ALTER TABLE public."Cesfampage_noticia" OWNER TO inacap;

--
-- TOC entry 223 (class 1259 OID 24632)
-- Name: Cesfampage_noticia_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public."Cesfampage_noticia" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cesfampage_noticia_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24617)
-- Name: Cesfampage_oirs; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public."Cesfampage_oirs" (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    correo character varying(100) NOT NULL,
    motivo character varying(50) NOT NULL,
    mensaje text NOT NULL,
    fecha_envio timestamp with time zone NOT NULL
);


ALTER TABLE public."Cesfampage_oirs" OWNER TO inacap;

--
-- TOC entry 219 (class 1259 OID 24616)
-- Name: Cesfampage_oirs_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public."Cesfampage_oirs" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cesfampage_oirs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24625)
-- Name: Cesfampage_trabajaconnosotros; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public."Cesfampage_trabajaconnosotros" (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    correo character varying(254) NOT NULL,
    area_postulacion character varying(50) NOT NULL,
    curriculum character varying(100),
    mensaje text NOT NULL,
    fecha_envio timestamp with time zone NOT NULL
);


ALTER TABLE public."Cesfampage_trabajaconnosotros" OWNER TO inacap;

--
-- TOC entry 221 (class 1259 OID 24624)
-- Name: Cesfampage_trabajaconnosotros_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public."Cesfampage_trabajaconnosotros" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cesfampage_trabajaconnosotros_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24661)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO inacap;

--
-- TOC entry 229 (class 1259 OID 24660)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 24669)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO inacap;

--
-- TOC entry 231 (class 1259 OID 24668)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24655)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO inacap;

--
-- TOC entry 227 (class 1259 OID 24654)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 24675)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO inacap;

--
-- TOC entry 236 (class 1259 OID 24683)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO inacap;

--
-- TOC entry 235 (class 1259 OID 24682)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 24674)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 24689)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO inacap;

--
-- TOC entry 237 (class 1259 OID 24688)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24747)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO inacap;

--
-- TOC entry 239 (class 1259 OID 24746)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24647)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO inacap;

--
-- TOC entry 225 (class 1259 OID 24646)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24601)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO inacap;

--
-- TOC entry 215 (class 1259 OID 24600)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: inacap
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 24777)
-- Name: django_session; Type: TABLE; Schema: public; Owner: inacap
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO inacap;

--
-- TOC entry 4417 (class 0 OID 24609)
-- Dependencies: 218
-- Data for Name: Cesfampage_evento; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public."Cesfampage_evento" (id, titulo, imagen, fecha_creacion, fecha_inicio, fecha_termino, descripcion, tipo_evento) FROM stdin;
1	Evento de Prueba1	eventos/OIP.jfif	2024-11-20 19:17:19.954987+00	2024-11-20	2024-11-30	Evento de prueba	Taller
\.


--
-- TOC entry 4423 (class 0 OID 24633)
-- Dependencies: 224
-- Data for Name: Cesfampage_noticia; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public."Cesfampage_noticia" (id, titulo, imagen, descripcion, fecha_creacion, evento_relacionado_id) FROM stdin;
2	Noticia prueba sincronización	noticias/image_2_Wro3MQZ.png	<p>texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto texto&nbsp;</p>	2024-12-10 19:43:55.771635+00	1
\.


--
-- TOC entry 4419 (class 0 OID 24617)
-- Dependencies: 220
-- Data for Name: Cesfampage_oirs; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public."Cesfampage_oirs" (id, nombre, apellido, correo, motivo, mensaje, fecha_envio) FROM stdin;
1	hola soy mati test oirs	apellido	inacap@inacap.cl	Felicitaciones	felicidades lo lograste!!!	2024-11-20 06:42:18.746203+00
2	Lucas	Cárcamop	lucas@gmail.com	Reclamo	Ta malo	2024-11-20 19:22:35.644289+00
\.


--
-- TOC entry 4421 (class 0 OID 24625)
-- Dependencies: 222
-- Data for Name: Cesfampage_trabajaconnosotros; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public."Cesfampage_trabajaconnosotros" (id, nombre, correo, area_postulacion, curriculum, mensaje, fecha_envio) FROM stdin;
1	hOLA	correo@correo.cl	Medicina	curriculums/Goku_9ZErcx6.mp3	quiero trabajar	2024-11-19 22:36:42.582689+00
2	Lucas Cárcamo	lucas@gmail.com	Administración	curriculums/asdasd.pdf	Quiero el puesto de trabajo de administracion	2024-11-20 19:26:01.976398+00
3	HolaholaHola	correo@correito.cl	Medicina	curriculums/imagen_2024-11-24_175957715.png	hola	2024-11-24 21:00:04.72994+00
\.


--
-- TOC entry 4429 (class 0 OID 24661)
-- Dependencies: 230
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 4431 (class 0 OID 24669)
-- Dependencies: 232
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 4427 (class 0 OID 24655)
-- Dependencies: 228
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add evento	7	add_evento
26	Can change evento	7	change_evento
27	Can delete evento	7	delete_evento
28	Can view evento	7	view_evento
29	Can add oirs	8	add_oirs
30	Can change oirs	8	change_oirs
31	Can delete oirs	8	delete_oirs
32	Can view oirs	8	view_oirs
33	Can add trabaja con nosotros	9	add_trabajaconnosotros
34	Can change trabaja con nosotros	9	change_trabajaconnosotros
35	Can delete trabaja con nosotros	9	delete_trabajaconnosotros
36	Can view trabaja con nosotros	9	view_trabajaconnosotros
37	Can add noticia	10	add_noticia
38	Can change noticia	10	change_noticia
39	Can delete noticia	10	delete_noticia
40	Can view noticia	10	view_noticia
\.


--
-- TOC entry 4433 (class 0 OID 24675)
-- Dependencies: 234
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$720000$WH5COsm6XJY1Bx0RtlJ58I$W4V0p2Ibxc6KJ1lk4izNgVQNhDEUe+eULZ3j6aOrAZc=	2024-12-11 02:38:03.070227+00	t	cesfam			aravenavasquez.r@gmail.com	t	t	2024-11-19 22:35:29.60439+00
\.


--
-- TOC entry 4435 (class 0 OID 24683)
-- Dependencies: 236
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 4437 (class 0 OID 24689)
-- Dependencies: 238
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 4439 (class 0 OID 24747)
-- Dependencies: 240
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 4425 (class 0 OID 24647)
-- Dependencies: 226
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	Cesfampage	evento
8	Cesfampage	oirs
9	Cesfampage	trabajaconnosotros
10	Cesfampage	noticia
\.


--
-- TOC entry 4415 (class 0 OID 24601)
-- Dependencies: 216
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	Cesfampage	0001_initial	2024-11-19 22:33:14.615681+00
2	contenttypes	0001_initial	2024-11-19 22:33:15.203253+00
3	auth	0001_initial	2024-11-19 22:33:19.544895+00
4	admin	0001_initial	2024-11-19 22:33:20.702695+00
5	admin	0002_logentry_remove_auto_add	2024-11-19 22:33:20.851242+00
6	admin	0003_logentry_add_action_flag_choices	2024-11-19 22:33:21.282806+00
7	contenttypes	0002_remove_content_type_name	2024-11-19 22:33:22.147535+00
8	auth	0002_alter_permission_name_max_length	2024-11-19 22:33:22.723651+00
9	auth	0003_alter_user_email_max_length	2024-11-19 22:33:23.297868+00
10	auth	0004_alter_user_username_opts	2024-11-19 22:33:23.586811+00
11	auth	0005_alter_user_last_login_null	2024-11-19 22:33:24.303416+00
12	auth	0006_require_contenttypes_0002	2024-11-19 22:33:24.589674+00
13	auth	0007_alter_validators_add_error_messages	2024-11-19 22:33:25.021035+00
14	auth	0008_alter_user_username_max_length	2024-11-19 22:33:25.743896+00
15	auth	0009_alter_user_last_name_max_length	2024-11-19 22:33:26.317768+00
16	auth	0010_alter_group_name_max_length	2024-11-19 22:33:26.894053+00
17	auth	0011_update_proxy_permissions	2024-11-19 22:33:27.18457+00
18	auth	0012_alter_user_first_name_max_length	2024-11-19 22:33:27.902692+00
19	sessions	0001_initial	2024-11-19 22:33:28.911452+00
20	Cesfampage	0002_alter_evento_tipo_evento	2024-11-20 06:05:59.050866+00
\.


--
-- TOC entry 4440 (class 0 OID 24777)
-- Dependencies: 241
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: inacap
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
vapr76bzoehk7keo0rilbcg5tbfmpflu	.eJxVjrlSxDAQRH-Fcgqr0jFaHSE5GblKx2gtMFZhSSQU_45dOGDT6X6v53tyfvTZjYabK2myE5ue_t-Cj--4HkF68-utkljXvpVAjgo500ZeasLl-ezeCWbf5p0GkyAiRI0iBykkByWT9hqQK0TI3ATOrylHBikZA0bpzGNWPqLyIRzSvwcOdXVLvdXR3eJbdxt-Dmx9H-GUw4XxC6OvzFgASwVRRiptHim1lO6SsfTy4d1XaaX7O-RhR4S24ko4lVSKE_n5BUrOWfY:1tL69L:1TlBEmb3b_Qe8kYA1LUKf8-H03I8raCWZj5qpywLri0	2024-12-10 20:14:03.823814+00
hhl096j8bxfjtdg9w7668yavb1lu2wxc	.eJxVjMsOgjAQRX_FdKs0M1OKhaV7v4FM20GqCAkPN8Z_FxIWur3n3PNWNS9zWy-TjHWKqlKoTr-b5_CQfgPxzv1t0GHo5zF5vSl6p5O-DlG6y-7-BVqe2vXtDZ4pGCdFaRtrgaPD2EjhYygMkDgXGi7EoDRQRgdoRIBd7uM5IOMWXbo5Pbl-pSnNvCYJKM8QM4IDUEW2Qqst5UR4BKgA1OcLn3ZFHw:1tDaP5:vy2us8Qydqi9J0U3ZmrWpKgqsNojNqXsAGlWfa40VMQ	2024-11-20 02:55:15.803281+00
8owtpoajpgswln58a0kmjnuao83698wg	.eJxVjj1TxSAQRf-Kk1YfA8vyCJT2dvYMH8tLNIYxgI3jfzcZU_javfecu9-D871Nrlfa3JwGO4jh6f8t-PhO6xGkN7_eCotlbdsc2FFhZ1rZS0m0PJ_dO8Hk67TTaBJGwjiSzEFJBahVGv2IBJoIM5gAcE05CkzJGDR6zBCz9pG0D-GQ_j1wqItbyq305hZfm9vos1Nt-whwwIuAixCvXFp5tQqZElJJfOTccr5L-tLmD---5jo3f4c8cLBqb0mGI0eEE_n5BUQTWdM:1tLDWw:W--BR_UzQZlXVKwNOXqQPe17tFAVhg-yZ6L1pnInA1E	2024-12-11 04:06:54.532061+00
3tip18dgc4rhlbn1r6j1ix05gtlocfcz	.eJxVjEEOwiAQRe_C2pCUDgIu3XsGMswMUjWQlHbVeHdt0oVu_3vvbyriupS4dpnjxOqiBnX63RLSU-oO-IH13jS1usxT0ruiD9r1rbG8rof7d1Cwl28NgYEEyMuYkx2tAWfZowcxTgSyCcmYM2cagDkECM5nQ9khicOUWL0_8wA44w:1tDeP4:HdaKK0DyguiKalFKy9nj_Z0XanTkfHM5WUsav6qKWbA	2024-11-20 07:11:30.097519+00
pz2l7q26xvfszbm2p3m6g8vd4nuyjp68	.eJxVjrtSxDAMRX-FScuuR1aU-FHSb0fv8UPZBEI8xA4Nw7-TDCnYVveec_XdOL_V0W2FVzelxjayufy_BR_feTmC9OaXexYxL3Wdgjgq4kyLuOXE88vZfRCMvow7TSZRZIqa2yF0bYekuqS9JkbFTAOagNinIUpKyRgySg8YB-UjKx_CIf174FBnN-d73qqbfalu5c-NS91HEJCuUl4RXkFZQgsoesRO62cAC7BLtrlOH959TWWq_gF5gt6StG0veqnAwIn8_AJFSVng:1tDfLe:bJAFd-k2rz6pe85BHeHyRFDVqs_U55NoeXNoJNmGcPg	2024-11-20 08:12:02.641069+00
pfixs0ez61d5vvvxxkmjexx4dz8ep5tw	.eJxVjrtuxCAQRX8lcptdBAPm4TL9dukRj2FN4hjFQJoo_x5bcZFt595z7nwP1vU2215xszkO08CGy_-bd-Ed1yOIb269FxLK2rbsyVEhZ1rJrURcXs7ug2B2dd5pYaIIKIJGnvzIRxBqjNppgaAQRQLjAWRMgYkYjRFG6QQhKRdQOe8P6d8Dh7rYpdxLb3ZxtdkNPzvWto8ABXFl7Ar0lcmJwcQ1UVxyKp8pnSjdJX1p-cPZr1xzcw_I04lIokctDJzIzy9F_Fns:1tDnJn:euvm5qeQtvHLKETqLJf2ifsYaDNWXGdB_eyVfvVpXHI	2024-11-20 16:42:39.011896+00
bmfovzjfli42d141haw1h3l4kwlbw4bw	.eJxVjj1TxSAQRf-Kk1YfA5vlESjt7ewZPpYXNIYxgI3jfzcZU_javfecu9-Ddb3NtlfabI6DGcTw9P_mXXin9Qjim1tvhYWyti17dlTYmVb2UiItz2f3TjC7Ou806oiBMEw0Ji9HCahknNyEBIoIE2gPcI0pCIxRa9RqShCScoGU8_6Q_j1wqItdyq30ZhdXm93os1Nt-whwwIsQF-CvQhtQhl-ZGhVH-ci54XyX9KXlD2e_cs3N3SEPOyKEkcBAotTiRH5-AUb2Wec:1tDqLy:1woh4aPOZu2KxMnr1WRh9XgtHlYHjd0AZDnmfWORymo	2024-11-20 19:57:06.74606+00
9t4hxx75afs63mn6amyf2j6yzkd6lv1j	.eJxVjEEOwiAQRe_C2pCUDgIu3XsGMswMUjWQlHbVeHdt0oVu_3vvbyriupS4dpnjxOqiBnX63RLSU-oO-IH13jS1usxT0ruiD9r1rbG8rof7d1Cwl28NgYEEyMuYkx2tAWfZowcxTgSyCcmYM2cagDkECM5nQ9khicOUWL0_8wA44w:1tL641:2VRIe9IJFyjXnya1LZ4t7GoxgTgqweqi8-nqcMl2r9M	2024-12-10 20:08:33.238465+00
\.


--
-- TOC entry 4446 (class 0 OID 0)
-- Dependencies: 217
-- Name: Cesfampage_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public."Cesfampage_evento_id_seq"', 1, true);


--
-- TOC entry 4447 (class 0 OID 0)
-- Dependencies: 223
-- Name: Cesfampage_noticia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public."Cesfampage_noticia_id_seq"', 2, true);


--
-- TOC entry 4448 (class 0 OID 0)
-- Dependencies: 219
-- Name: Cesfampage_oirs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public."Cesfampage_oirs_id_seq"', 2, true);


--
-- TOC entry 4449 (class 0 OID 0)
-- Dependencies: 221
-- Name: Cesfampage_trabajaconnosotros_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public."Cesfampage_trabajaconnosotros_id_seq"', 3, true);


--
-- TOC entry 4450 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 4451 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 4452 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- TOC entry 4453 (class 0 OID 0)
-- Dependencies: 235
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 4454 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- TOC entry 4455 (class 0 OID 0)
-- Dependencies: 237
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 4456 (class 0 OID 0)
-- Dependencies: 239
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 4457 (class 0 OID 0)
-- Dependencies: 225
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- TOC entry 4458 (class 0 OID 0)
-- Dependencies: 215
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: inacap
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- TOC entry 4208 (class 2606 OID 24615)
-- Name: Cesfampage_evento Cesfampage_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public."Cesfampage_evento"
    ADD CONSTRAINT "Cesfampage_evento_pkey" PRIMARY KEY (id);


--
-- TOC entry 4215 (class 2606 OID 24639)
-- Name: Cesfampage_noticia Cesfampage_noticia_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public."Cesfampage_noticia"
    ADD CONSTRAINT "Cesfampage_noticia_pkey" PRIMARY KEY (id);


--
-- TOC entry 4210 (class 2606 OID 24623)
-- Name: Cesfampage_oirs Cesfampage_oirs_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public."Cesfampage_oirs"
    ADD CONSTRAINT "Cesfampage_oirs_pkey" PRIMARY KEY (id);


--
-- TOC entry 4212 (class 2606 OID 24631)
-- Name: Cesfampage_trabajaconnosotros Cesfampage_trabajaconnosotros_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public."Cesfampage_trabajaconnosotros"
    ADD CONSTRAINT "Cesfampage_trabajaconnosotros_pkey" PRIMARY KEY (id);


--
-- TOC entry 4227 (class 2606 OID 24773)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4232 (class 2606 OID 24704)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4235 (class 2606 OID 24673)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4229 (class 2606 OID 24665)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4222 (class 2606 OID 24695)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4224 (class 2606 OID 24659)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4243 (class 2606 OID 24687)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4246 (class 2606 OID 24719)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4237 (class 2606 OID 24679)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4249 (class 2606 OID 24693)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4252 (class 2606 OID 24733)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4240 (class 2606 OID 24768)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4255 (class 2606 OID 24754)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4217 (class 2606 OID 24653)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4219 (class 2606 OID 24651)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4206 (class 2606 OID 24607)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4259 (class 2606 OID 24783)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4213 (class 1259 OID 24645)
-- Name: Cesfampage_noticia_evento_relacionado_id_f9a3808f; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX "Cesfampage_noticia_evento_relacionado_id_f9a3808f" ON public."Cesfampage_noticia" USING btree (evento_relacionado_id);


--
-- TOC entry 4225 (class 1259 OID 24774)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4230 (class 1259 OID 24715)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4233 (class 1259 OID 24716)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4220 (class 1259 OID 24701)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4241 (class 1259 OID 24731)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4244 (class 1259 OID 24730)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4247 (class 1259 OID 24745)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4250 (class 1259 OID 24744)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4238 (class 1259 OID 24769)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4253 (class 1259 OID 24765)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4256 (class 1259 OID 24766)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4257 (class 1259 OID 24785)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4260 (class 1259 OID 24784)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: inacap
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4261 (class 2606 OID 24640)
-- Name: Cesfampage_noticia Cesfampage_noticia_evento_relacionado_i_f9a3808f_fk_Cesfampag; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public."Cesfampage_noticia"
    ADD CONSTRAINT "Cesfampage_noticia_evento_relacionado_i_f9a3808f_fk_Cesfampag" FOREIGN KEY (evento_relacionado_id) REFERENCES public."Cesfampage_evento"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4263 (class 2606 OID 24710)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4264 (class 2606 OID 24705)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4262 (class 2606 OID 24696)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4265 (class 2606 OID 24725)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4266 (class 2606 OID 24720)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4267 (class 2606 OID 24739)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4268 (class 2606 OID 24734)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4269 (class 2606 OID 24755)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4270 (class 2606 OID 24760)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: inacap
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-12-11 01:05:47

--
-- PostgreSQL database dump complete
--

