# Generated by Django 5.0.7 on 2024-10-22 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="eventos/")),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("descripcion", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("", "Seleccione un tipo de evento"),
                            ("Evento", "Evento"),
                            ("Taller", "Taller"),
                            ("Campaña", "Campaña"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="noticias/")),
                ("descripcion", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "evento_relacionado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Cesfampage.evento",
                    ),
                ),
            ],
        ),
    ]
