# Generated by Django 5.0.7 on 2024-11-20 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, upload_to='eventos/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=900, null=True)),
                ('tipo_evento', models.CharField(choices=[('', 'Seleccione un tipo de evento'), ('Evento', 'Evento'), ('Taller', 'Taller'), ('Campaña-Semestral', 'Campaña-Semestral'), ('Campaña-Mensual', 'Campaña-Mensual')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('motivo', models.CharField(choices=[('', 'Seleccione el motivo'), ('Reclamo', 'Reclamo'), ('Consulta', 'Consulta'), ('Sugerencia', 'Sugerencia'), ('Felicitaciones', 'Felicitaciones'), ('Otro', 'Otro')], max_length=50)),
                ('mensaje', models.TextField(max_length=900)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajaConNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('area_postulacion', models.CharField(choices=[('Medicina', 'Medicina'), ('Enfermería', 'Enfermería'), ('Administración', 'Administración'), ('Servicios Generales', 'Servicios Generales'), ('Otro', 'Otro')], max_length=50)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, upload_to='noticias/')),
                ('descripcion', models.TextField(blank=True, max_length=900, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cesfampage.evento')),
            ],
        ),
    ]
