# Generated by Django 5.0.7 on 2024-11-13 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cesfampage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oirs",
            name="fecha_envio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
