# Generated by Django 5.1.1 on 2024-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cesfampage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('', 'Seleccione un tipo de evento'), ('Evento', 'Evento'), ('Taller', 'Taller'), ('Campaña-Semestral', 'Campaña-Semestral'), ('Campaña-Mensual', 'Campaña-Mensual')], max_length=50),
        ),
    ]
