# Generated by Django 5.0.7 on 2024-12-11 04:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cesfampage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descripcion",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="descripcion",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="evento_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Cesfampage.evento",
            ),
        ),
        migrations.AlterField(
            model_name="oirs",
            name="mensaje",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="trabajaconnosotros",
            name="mensaje",
            field=models.TextField(max_length=300),
        ),
    ]
